#!/usr/bin/env bash
# install nginx
# listening on port 80
# returns a page containing string when sent a GET request at root
apt-get update
apt-get -y install nginx
service nginx start
rm /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
