#!/usr/bin/env bash
# shellcheck disable=SC2154
# Configure new webserver to run Nginx and set up so that its HTTP response contains a custom header
apt-get update
apt-get install -y nginx
sudo mkdir -p /var/www/html
sudo echo "Hello World!" > /var/www/html/index.html
service nginx start
sed -i "20i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
service nginx restart
