#!/bin/bash
# Configure ufw to forward port 8080/TCP to port 80/TCP on web-01

# Enable ufw
sudo ufw enable

# Add forwarding rule to ufw configuration file
echo "
# Port forwarding rule
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
" | sudo tee -a /etc/ufw/before.rules > /dev/null

# Reload ufw to apply changes
sudo ufw reload

