#!/usr/bin/env bash
# Write a Bash script that configures container to run nginx as nginx user, listen on all active IPs port 8080

sed -i 's/user\s*www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/lib/nginx
nginx -g 'daemon off;'

sudo service nginx restart

